- defaults:
    link:
        relink: true
        force: true

- clean:
    '~/':
        force: true
    '~/.config':
        recursive: true

- shell:
    - description:  initialize files
      command: if [ ! -d ~/.config ]; then mkdir ~/.config; fi

- link:
    ~/.zshrc: zsh/zshrc
    ~/.p10k.zshrc: zsh/p10k.zsh
    ~/.editorconfig: editorconfig
    ~/.vimrc: vim/vimrc
    ~/.vim: vim/vim
    ~/.config/tmux: tmux
    ~/bin: bin
    ~/.scmbrc: scm_breeze/scmbrc
    ~/.git.scmbrc: scm_breeze/git.scmbrc

# install homebrew
- if:
    - cond: '! which brew &> /dev/null '
      met:
        - if:
            - cond: '[[ `uname` = Linux ]]'
              met:
                - if:
                    - cond: '! which yum &> /dev/null'
                      met:
                        - defaults:
                            yum:
                                sudo: True
                        - yum:
                            Development Tools:
                                group: True
                        - yum: [procps-ng, curl, file, git]
                    - cond: '! which apt &> /dev/null '
                      met:
                        - defaults:
                            apt:
                                sudo: True
                        - apt: [build-essential procps curl file git]
                - shell:
                    - [ NONINTERACTIVE=1 /bin/bash -c  ~/.dotfiles/libs/homebrew-install/install.sh, Installing Homebrew]

- brew: [awscli coreutils ctags]
- brew:
    - fzf
    - gcc
    - git
    - jq
    - maven
    - node
    - openssh
    - readline
    - tmux
    - tree
    - tre
    - vim
    - wget
    - zsh
    - zsh-completions

- if:
    - cond: '[ `uname` = Darwin ]'
      met:
        - shell:
            - [cp fonts/MesloLGS\ NF\ Bold\ Italic.ttf /Library/Fonts/MesloLGS\ NF\ Bold\ Italic.ttf, copying MesloLGS NF Bold Italic.ttf]
            - [cp fonts/MesloLGS\ NF\ Bold.ttf /Library/Fonts/MesloLGS\ NF\ Bold.ttf, copying MesloLGS NF Bold.ttf]
            - [cp fonts/MesloLGS\ NF\ Italic.ttf /Library/Fonts/MesloLGS\ NF\ Italic.ttf, copying MesloLGS NF Italic.ttf]
            - [cp fonts/MesloLGS\ NF\ Regular.ttf /Library/Fonts/MesloLGS\ NF\ Regular.ttf, copying MesloLGS NF Regular.ttf]
        - cask:
            - 1password
            - 1password-cli
            - alfred
            - caffeine
            - dbeaver-community
            - notunes
            - signal
            - vlc
            - zoom
        - if:
            # Certain applications are installed in other ways on work machines
            # Or is for personal machines
            # run `export WORK_LAPTOP=1` if this is a work machine
            - cond: '[ ! -n "${WORK_LAPTOP+1}" ]'
              met:
                - brew:
                    - yt-dlp
                - cask:
                    - visual-studio-code
                    - slack
        - link:
            ~/Library/Application Support/Code/User/keybindings.json: scripts/vs_configs/keybindings.json
            ~/Library/Application Support/Code/User/settings.json: scripts/vs_configs/settings.json
