" Include default global config
if filereadable("/etc/vimrc")
    source /etc/vimrc
endif

" Vimscript file settings ---------------------- {{{
let b:did_ftplugin = 1
augroup filetype_vim
    autocmd!
    autocmd FileType vim setlocal foldmethod=marker
augroup END
" }}}

" Pathogen -------------------------------- {{{
" "https://github.com/tpope/vim-pathogen"
runtime bundle/vim-pathogen/autoload/pathogen.vim
execute pathogen#infect()
" }}}

" Main options and settings --------------------- {{{
" Default options
" "https://wiki.archlinux.org/index.php/vim/.vimrc"
" colorscheme gruvbox
colorscheme dracula
" colorscheme solarized
" colorscheme molokai
" let g:molokai_original = 1
" let g:rehash256 = 1

syntax on
filetype plugin indent on

" Space leader
nnoremap <space> <nop>
let mapleader=" "

" set textwidth=79
set autoindent
set background=dark
set backspace=2
set colorcolumn=+1        " highlight column after 'textwidth'
set hlsearch
set ignorecase
set incsearch
set list
set listchars=eol:¬,tab:>-,trail:•,extends:>,precedes:<
set mouse=a
set number
set nocompatible
set relativenumber
set ruler
set showcmd
set showmatch
set smartcase

" Trailing whitespace highlighting -------------- {{{
" "http://vim.wikia.com/wiki/Highlight_unwanted_spaces"
highlight ExtraWhitespace ctermbg=red guibg=red
match ExtraWhitespace /\s\+$/
autocmd BufWinEnter * match ExtraWhitespace /\s\+$/
autocmd InsertEnter * match ExtraWhitespace /\s\+\%#\@<!$/
autocmd InsertLeave * match ExtraWhitespace /\s\+$/
autocmd BufWinLeave * call clearmatches()
" }}}
" }}}

" Global Mappings -------------------------------------- {{{
" So much thanks to Steve Losh's "Learn Vimscript the Hard Way"
" "http://learnvimscriptthehardway.stevelosh.com/chapters/06.html"
" "http://learnvimscriptthehardway.stevelosh.com/chapters/07.html"

" Insert Mode ----------------------------------- {{{
" jk/kj as Escape ------------------------------- {{{
inoremap jk <esc>
inoremap kj <esc>
" }}}
" }}}

" Selectors ------------------------------------- {{{
" More thanks to Steve Losh's "Learn Vimscript the Hard Way"
" "http://learnvimscriptthehardway.stevelosh.com/chapters/15.html"

" Inside _P_arentheses
onoremap p i(

" Inside curly breaces
onoremap o i{
" }}}

" Normal Mode ----------------------------------- {{{
" Arrow Key Line Movement ----------------------- {{{
" Moving lines up and down with the arrow keys. As inspired by June 15' SF Vim
" meetup and "http://codingfearlessly.com/2012/08/21/vim-putting-arrows-to-use/"
nmap <Up> [e
nmap <Down> ]e
vmap <Up> [egv
vmap <Down> ]egv
" }}}
" Crosshair ------------------------------------- {{{
" Set up crosshair, toggle with <leader>c in normal mode
:hi CursorLine cterm=NONE ctermbg=darkgrey ctermfg=white guibg=darkgrey guifg=white
:hi CursorColumn cterm=NONE ctermbg=darkgrey ctermfg=white guibg=darkgrey guifg=white
:nnoremap <leader>c :set cursorline! cursorcolumn!<CR>
" }}}
" Git ------------------------------------------- {{{
" gst - Open Git status
nnoremap <leader>gst :Gstatus<cr>

" gco - Open Git commit
nnoremap <leader>gco :Gcommit<cr>
" }}}
" Left/Right Shift ------------------------------ {{{
nnoremap <leader>l >>
nnoremap <leader>h <<
" }}}
" Other ----------------------------------------- {{{
" p - Duplicate line
nnoremap <leader>p yyp

" c - _C_lear the current search
 noremap <leader>cl :noh<cr>

" sp - _SP_elling fix with first result
nnoremap <leader>sp z=1<cr><cr>

" <space><space> - toggles fold
nnoremap <leader><space> za
" }}}
" Taglist Toggle -------------------------------- {{{
:nnoremap <leader>t :Tlist<CR>
" }}}
" Vimrc ----------------------------------------- {{{
" ev - _E_dit _V_im config
nnoremap <leader>ev :vsplit $MYVIMRC<cr>

" sv - _S_ource _V_im config
nnoremap <leader>sv :source $MYVIMRC<cr>
" }}}
" }}}

" Trim on Save ----------------------------------- {{{
" trim spaces at EOL
augroup trimWhitespace
    autocmd!
    autocmd BufWritePre * :%s/\s\+$//e
augroup END
" }}}

" Folding ----------------------------------- {{{
" Why not use the space or return keys to toggle folds?
nnoremap <space> za
nnoremap <CR> za
vnoremap <space> zf
" }}}
" }}}

" Plugins --------------------------------------- {{{
" Airline --------------------------------------- {{{
" "https://github.com/bling/vim-airline"
let g:airline_powerline_fonts = 1
set encoding=utf-8
set laststatus=2
" }}}
" Ctrlp ----------------------------------------- {{{
let g:ctrlp_working_path_mode = 'ca'
" }}}
" undotree ----------------------------------------- {{{
nnoremap <F5> :UndotreeToggle<CR>
" }}}
" EditorConfig -------------------------------------- {{{
packadd! editorconfig
" }}}
" NERDTree -------------------------------------- {{{
" Start if no file opened
"autocmd vimenter * if !argc() | NERDTree | endif
" Assign command to TAB
map <TAB> :NERDTreeToggle<CR>
" Fix encoding issues surrounding arrows
" "https://superuser.com/questions/387777/what-could-cause-strange-characters-in-vim"
let g:NERDTreeDirArrows=0
let g:NERDTreeShowHidden=1
" }}}
" RainbowParentheses ---------------------------- {{{
" Auto enable rainbow parentheses
au VimEnter * RainbowParenthesesToggle
au Syntax * RainbowParenthesesLoadRound
au Syntax * RainbowParenthesesLoadSquare
au Syntax * RainbowParenthesesLoadBraces
let g:rbpt_colorpairs = [
    \ ['brown',       'RoyalBlue3'],
    \ ['Darkblue',    'SeaGreen3'],
    \ ['darkgray',    'DarkOrchid3'],
    \ ['darkgreen',   'firebrick3'],
    \ ['darkcyan',    'RoyalBlue3'],
    \ ['darkred',     'SeaGreen3'],
    \ ['darkmagenta', 'DarkOrchid3'],
    \ ['brown',       'firebrick3'],
    \ ['gray',        'RoyalBlue3'],
    \ ['black',       'SeaGreen3'],
    \ ['darkmagenta', 'DarkOrchid3'],
    \ ['Darkblue',    'firebrick3'],
    \ ['darkgreen',   'RoyalBlue3'],
    \ ['darkcyan',    'SeaGreen3'],
    \ ['darkred',     'DarkOrchid3'],
    \ ['red',         'firebrick3'],
    \ ]
let g:rbpt_max = 16
let g:rbpt_loadcmd_toggle = 0
" }}}
" Taglist --------------------------------------- {{{
" "https://caffeinatedcode.wordpress.com/2009/11/16/simple-latex-ctags-and-taglist/"
let tlist_tex_settings = 'latex;l:labels;s:sections;t:subsections;u:subsubsections'
" }}}
" Vim-auto-save --------------------------------- {{{
" "https://github.com/vim-scripts/vim-auto-save"
" Enable auto saving at startup (can use :AutoSaveToggle otherwise)
let g:auto_save = 1

" Don't save while in insert mode
let g:auto_save_in_insert_mode = 0

" This plugin changes vim's updatetime option.
" If it breaks things, uncomment this
"let g:auto_save_no_updatetime = 1
" }}}
" }}}

" Helpful changes/Hacks --------------------------------------- {{{
" Prevent loading more stuff  --------------------------------------- {{{
" having Ex mode start or showing me the command history
" is a complete pain in the ass if i mistype
nnoremap Q <silent>
nnoremap q: <silent>
nnoremap K <silent>
" }}}

" Change folding methods/* {{{ */
augroup vimrc
  au BufReadPre * setlocal foldmethod=indent
  au BufWinEnter * if &fdm == 'indent' | setlocal foldmethod=manual | endif
augroup END
" }}}
" }}}
