#!/bin/zsh

alias ll="ls -l"
alias lla="ls -al"

#GIT STUFF
alias gl='git log'
alias gcm='git checkout mainline'

# Undo a `git push`
alias undopush="git push -f origin HEAD^:master"
alias gfpo="git push -f origin"
alias gpo="git push -u origin $(parse_git_branch)"

# git root
alias gr='[ ! -z `git rev-parse --show-cdup` ] && cd `git rev-parse --show-cdup || pwd`'

# this will do 3 things
# first, get the latest master
# then delete all merged branches
# then delete all squash and merged branches (since they don't show up as merged)
# last part lovingly stolen from https://medium.com/opendoor-labs/cleaning-up-branches-with-githubs-squash-merge-43138cc7585e
alias rmMergedBranches='git checkout master && git pull && git branch --merged | egrep -v "(^\*|master)" | xargs git branch -d  && comm -12 <(git branch | sed "s/ *//g") <(git remote prune origin | sed "s/^.*origin\///g") | xargs -L1 -J % git branch -D %'

# Enhanced WHOIS lookups
alias whois="whois -h whois-servers.net"

# Flush Directory Service cache
alias flush="dscacheutil -flushcache"

# View HTTP traffic
alias sniff="sudo ngrep -d 'en1' -t '^(GET|POST) ' 'tcp and port 80'"
alias httpdump="sudo tcpdump -i en1 -n -s 0 -w - | grep -a -o -E \"Host\: .*|GET \/.*\""

# Trim new lines and copy to clipboard
alias trimcopy="tr -d '\n' | pbcopy"

# Recursively delete `.DS_Store` files
alias cleanup="find . -name '*.DS_Store' -type f -ls -delete"

# File size
alias fs="stat -f \"%z bytes\""

# Empty the Trash on all mounted volumes and the main HDD
alias emptytrash="sudo rm -rfv /Volumes/*/.Trashes; rm -rfv ~/.Trash"

# Hide/show all desktop icons (useful when presenting)
alias hidedesktop="defaults write com.apple.finder CreateDesktop -bool false && killall Finder"
alias showdesktop="defaults write com.apple.finder CreateDesktop -bool true && killall Finder"


# PlistBuddy alias, because sometimes `defaults` just doesn’t cut it
alias plistbuddy="/usr/libexec/PlistBuddy"

# One of @janmoesen’s ProTip™s
for method in GET HEAD POST PUT DELETE TRACE OPTIONS; do
	alias "$method"="lwp-request -m '$method'"
done

# Stuff I never really use but cannot delete either because of http://xkcd.com/530/
alias stfu="osascript -e 'set volume output muted true'"
alias pumpitup="osascript -e 'set volume 10'"
# TODO look how to do this in osascript
#alias hax="growlnotify -a 'Activity Monitor' 'System error' -m 'WTF R U DOIN'"
alias turnOnBluetooth="blueutil -p 1"

alias df="df -h"
alias cls='clear && ls'
alias scp='scp -2Cr'

# wget w/o letting the server know we are using wget
alias wget='wget --user-agent=""'

# docker-related fun
alias dc="docker compose"
alias dps="docker ps --format 'table {{.ID}}\t{{.Names}}\t{{.Ports}}\t{{.Status}}'"
alias dpn="docker ps --format '{{.Names}}'"

# regular fun
alias downloadFromYoutube='yt-dlp -x --audio-format mp3 --audio-quality 0 --output "%(title)s.%(ext)s" --metadata-from-title "(?P<title>.+)"'

# test stuff in go and show coverage
alias gotwc='go test -coverprofile=coverage.out && go tool cover -html=coverage.out && rm coverage.out'


# docker and k8s commands I'm not sure about yet
alias dexec="docker exec -it"
alias k='kubectl'

# don't save verification details
alias sshno='ssh -o "UserKnownHostsFile=/dev/null" -o "StrictHostKeyChecking=no"'
alias scpno='scp -o "UserKnownHostsFile=/dev/null" -o "StrictHostKeyChecking=no"'
alias rsyncno='rsync -e"sshno"'

alias nv='nvim'
