#!/bin/sh
#
# Homebrew
#
# This installs php with a few extra kicks that I personally like/use
#   and taps certain repos that I need
#
brew update
brew upgrade

# Install GNU core utilities (those that come with OS X are outdated)
brew install coreutils
echo "Don’t forget to add $(brew --prefix coreutils)/libexec/gnubin to \$PATH."

# Install GNU `find`, `locate`, `updatedb`, and `xargs`, g-prefixed
brew install findutils
# Install Bash 4
brew install bash

# Install wget with IRI support
brew install wget --enable-iri

brew tap homebrew/dupes
brew install homebrew/dupes/grep
brew tap josegonzalez/homebrew-php
brew install dos2unix libmemcached nginx readline bash-completion mcrypt node redis git memcached mongodb jsl  phantomjs graphicsmagick   jsmin multitail
brew install wget --enable-iri
brew install php54 --with-fpm --with-mysql --without-pear
brew install php54-mongo php54-memcached php54-memcache php54-apc php54-mcrypt \
  php54-redis php54-xdebug php54-xhprof phplint ack tmux php54-yaml \
  php54-igbinary v8 php54-oauth
pecl install v8js-beta

# Install everything else
brew install ack rename tree

# Remove outdated versions from the cellar
#brew cleanup

