#!/bin/sh
#
# Homebrew
#
# This installs php with a few extra kicks that I personally like/use
#   and taps certain repos that I need
#
brew update
brew upgrade

# Install GNU core utilities (those that come with OS X are outdated)
brew install coreutils
brew install apple-gcc42
echo "Don’t forget to add $(brew --prefix coreutils)/libexec/gnubin to \$PATH."

# Install GNU `find`, `locate`, `updatedb`, and `xargs`, g-prefixed
brew install findutils
# Install Bash 4
brew install bash

# Install wget with IRI support
brew install wget --enable-iri

brew tap homebrew/dupes
brew install homebrew/dupes/grep
brew install dos2unix libmemcached nginx readline bash-completion mcrypt \
   node redis git memcached mongodb jsl phantomjs graphicsmagick jsmin \
    multitail unrar p7zip
brew install phplint ack tmux v8
pecl install v8js-beta beanstalkd
pecl install -f ssh2

brew install vim --override-system-vi --with-lua --with-perl --with-tcl
# ctags for vim
brew install ctags

brew install lame
brew install ffmpeg --with-openssl --with-openjpeg --with-tools --with-libvorbis --with-libvpx
brew install youtube-dl

curl http://python-distribute.org/distribute_setup.py | sudo python
curl https://raw.github.com/pypa/pip/master/contrib/get-pip.py | sudo python
sudo pip install --upgrade fabric pssh

# Install everything else
brew install ack rename tree

brew install elasticsearch;
#curl -sS https://getcomposer.org/installer | php
# install the mongodb river extension
$(dirname $(realpath $(which elasticsearch)))/plugin  --install com.github.richardwilly98.elasticsearch/elasticsearch-river-mongodb/1.7.3

# install cask, chrome, and quick look extensions
brew tap phinze/homebrew-cask
brew install brew-cask
brew cask install google-chrome
brew cask install qlcolorcode
brew cask install qlstephen
brew cask install qlmarkdown quicklook-json
brew cask install qlprettypatch
brew cask install quicklook-csv
brew cask install betterzipql
brew cask install webp-quicklook
brew cask install suspicious-package

qlmanage -r

brew cask install caffeine
brew cask install alfred
brew cask install clipmenu
brew cask install mou

# install wine
brew tap caskroom/cask
brew cask install java xquartz
brew install wine


# Remove outdated versions from the cellar
#brew cleanup

