#!/bin/sh
#
# Homebrew
#
# This installs php with a few extra kicks that I personally like/use
#   and taps certain repos that I need
#
brew update
brew upgrade

# Install GNU core utilities (those that come with OS X are outdated)
brew install coreutils
brew install apple-gcc42
echo "Don’t forget to add $(brew --prefix coreutils)/libexec/gnubin to \$PATH."

# Install GNU `find`, `locate`, `updatedb`, and `xargs`, g-prefixed
brew install findutils
# Install Bash 4
brew install bash

# Install wget with IRI support
brew install wget

brew install dos2unix libmemcached nginx readline bash-completion mcrypt \
   node redis git memcached jsl phantomjs graphicsmagick jsmin \
    multitail unrar p7zip
brew install phplint ack tmux v8
pecl install v8js-beta beanstalkd
pecl install -f ssh2

brew install vim
# ctags for vim
brew install ctags

brew install lame
brew install ffmpeg
brew install youtube-dl

# Install everything else
brew install ack rename tree

brew install elasticsearch;
#curl -sS https://getcomposer.org/installer | php
# install the mongodb river extension
$(dirname $(realpath $(which elasticsearch)))/plugin  --install com.github.richardwilly98.elasticsearch/elasticsearch-river-mongodb/1.7.3

# install cask, chrome, and quick look extensions
brew tap phinze/homebrew-cask
brew install brew-cask
brew install cask mongodb
brew install cask google-chrome
brew install cask qlcolorcode
brew install cask qlstephen
brew install cask qlmarkdown quicklook-json
brew install cask qlprettypatch
brew install cask quicklook-csv
brew install cask betterzipql
brew install cask webp-quicklook
brew install cask suspicious-package
brew install cask visual-studio-code
brew install cask slack
brew install cask docker && open /Applications/Docker.app
brew install cask signal

qlmanage -r

brew install cask caffeine
brew install cask alfred
brew install cask clipmenu
brew install cask mou

# install wine
brew tap homebrew/cask
brew install cask java xquartz
brew install wine

# Remove outdated versions from the cellar
#brew cleanup

