#!/bin/sh

# git related
code --install-extension eamodio.gitlens
# vim keybindings
code --install-extension vscodevim.vim
# Golang extension
code --install-extension ms-vscode.go
# Docker Extension
code --install-extension peterjausovec.vscode-docker
# PHP intellisense
code --install-extension felixfbecker.php-intellisense


for config in ${PWD}/scripts/vs_configs/*; do
        ln -s $config ~/Library/Application\ Support/Code/User
done

